<?php

return [
    'authorization' => env('AUTHORIZATION', true),
    'token_expired' => 5256000, // 10 years
    'paginate' => 50,
    's3_url' => env('AWS_S3_ATM_URL'), // Base URL for Amazon Web Service S3.
    'cache_expired' => [
        'default' => 24 * 60,
    ],

    // Register queue-priorities
    'jobs' => [
        'queue_process_kol_search' => 'high',
        'queue_process_kol_report' => 'high',
    ],

    // Client Id of hypeauditor (SANDBOX)
    'clientId' => env('CLIENT_ID', '360838'),
    'apiToken' => env('API_TOKEN', '$2y$04$Ai3PO.ApJUZd2tSpIEvrwuJowWPOVY5DwCE4RNnTVTD6ayQHKtZh6'),
    'email_not_exits' => 'email.not_exits',
    'mail_subject' => 'ログインIDのご確認及びパスワードの再設定',
    'mail_from_address' => env('MAIL_FROM_ADDRESS'),
    'mail_from_name' => env('MAIL_FROM_NAME'),
    'app_fe_url' => env('APP_FE_URL'),
    'valid_token_expired' => 1440,
    'token_expired_message' => 'token_expired',
    'token_invalid_message' => 'token_invalid',
    'user_not_found_message' => 'user_not_found',
    'user_payment' => [
        'plan_in_days' => 30,
        'plan_errors' => [
            'page_search_number_error' => 'plan.page_search_number_error',
            'profile_view_number_error' => 'plan.profile_view_number_error',
            'export_csv_number_error' => 'plan.export_csv_number_error',
            'campaign_register_number_error' => 'plan.campaign_register_number_error',
            'free_trial_error' => 'plan.free_trial_error',
        ],
        'plan_types' => [
            'free_trial' => 0,
            'basic' => 1,
            'silver' => 2,
            'gold' => 3,
            'order_made' => 4,
        ]
    ],

    'ages_group' => [
        'age13-17' => [
            'title' => '13-17',
            'value' => 0,
        ],
        'age18-24' => [
            'title' => '28-24',
            'value' => 0,
        ],
        'age25-34' => [
            'title' => '25-34',
            'value' => 0,
        ],
        'age35-44' => [
            'title' => '35-44',
            'value' => 0,
        ],
        'age45-64' => [
            'title' => '45-64',
            'value' => 0,
        ],
    ],

    'ages_mapping' => 'age45-64',

    'ages_group_merge' => ['age45-54', 'age55-64'],

    'performance_blogger_hashtags' => '180d',

    'demography' => [
        'male' => '男',
        'male_title' => 'Male',
        'female' => '女',
        'female_title' => 'Female',
    ],

    'campaign_status' => [
        'confirming' => 0,
        'discussing' => 1,
        'ng' => 2,
        'ok' => 3,
        'product_sent' => 4,
        'waiting_for_draft' => 5,
        'waiting_for_post' => 6,
        'waiting_for_insight' => 7,
        'done' => 8,
    ],

    'languages' => [
        'am' => 'Amharic',
        'ar' => 'Arabic',
        'eu' => 'Basque',
        'bn' => 'Bengali',
        'en-GB' => 'English (UK)',
        'pt-BR' => 'Portuguese (Brazil)',
        'bg' => 'Bulgarian',
        'ca' => 'Catalan',
        'chr' => 'Cherokee',
        'hr' => 'Croatian',
        'cs' => 'Czech',
        'da' => 'Danish',
        'nl' => 'Dutch',
        'en' => 'English ',
        'et' => 'Estonian',
        'fil' => 'Filipino',
        'fr' => 'French',
        'de' => 'German',
        'el' => 'Greek',
        'gu' => 'Gujarati',
        'iw' => 'Hebrew',
        'hi' => 'Hindi',
        'hu' => 'Hungarian',
        'is' => 'Icelandic',
        'id' => 'Indonesian',
        'it' => 'Italian',
        'ja' => 'Japanese',
        'kn' => 'Kannada',
        'lv' => 'Latvian',
        'lt' => 'Lithuanian',
        'ms' => 'Malay',
        'ml' => 'Malayalam',
        'mr' => 'Marathi',
        'no' => 'Norwegian',
        'pl' => 'Polish',
        'pt' => 'Portuguese (Portugal)',
        'ro' => 'Romanian',
        'ru' => 'Russian',
        'sr' => 'Serbian',
        'zh-CN' => 'Chinese (PRC)',
        'sk' => 'Slovak',
        'sl' => 'Slovenian',
        'es' => 'Spanish',
        'sw' => 'Swahili',
        'ta' => 'Tamil',
        'te' => 'Telugu',
        'th' => 'Thai',
        'zh-TW' => 'Chinese (Taiwan)',
        'tr' => 'Urdu',
        'uk' => 'Ukrainian',
        'vi' => 'Vietnamese',
        'cy' => 'Welsh'
    ],

    'campaign_detail_posts_report_type' => [
        'feed' => 1,
        'story' => 2,
        'reel' => 3,
    ],

    'export_kol' => [
        'username' => 'アカウント名',
        'country' => '国',
        'full_name' => '名前',
        'url' => 'アカウントURL',
        'follower_count' => 'フォロワー数',
        'engagement_rate' => 'エンゲージメント',
        'male_rate' => 'フォロワーの男性割合',
        'male_13_17_rate' => 'フォロワーの13-17歳の男性の割合',
        'male_18_24_rate' => 'フォロワーの18-24歳の男性の割合',
        'male_25_34_rate' => 'フォロワーの25-34歳の男性の割合',
        'male_35_44_rate' => 'フォロワーの35-44歳の男性の割合',
        'male_45_64_rate' => 'フォロワーの45-64歳の男性の割合',
        'female_rate' => 'フォロワーの女性割合',
        'female_13_17_rate' => 'フォロワーの13-17歳の女性の割合',
        'female_18_24_rate' => 'フォロワーの18-24歳の女性の割合',
        'female_25_34_rate' => 'フォロワーの25-34歳の女性の割合',
        'female_35_44_rate' => 'フォロワーの35-44歳の女性の割合',
        'female_45_64_rate' => 'フォロワーの45-64歳の女性の割合',
        'country_1st_follower' => 'フォロワーの所在地１位',
        'country_2th_follower' => 'フォロワーの所在地2位',
        'country_3rd_follower' => 'フォロワーの所在地3位',
        'hash_tag_er_1st' => 'ハッシュタグエンゲージメント１位',
        'hash_tag_er_2th' => 'ハッシュタグエンゲージメント2位',
        'hash_tag_er_3rd' => 'ハッシュタグエンゲージメント3位',
        'hash_tag_er_4th' => 'ハッシュタグエンゲージメント4位',
        'hash_tag_er_5th' => 'ハッシュタグエンゲージメント5位',
        'audience_interests_1st' => '興味１位',
        'audience_interests_2th' => '興味2位',
        'audience_interests_3rd' => '興味3位',
        'audience_interests_4th' => '興味4位',
        'audience_interests_5th' => '興味5位',
        'audience_brand_mentions_1st' => 'ブランド属性1位',
        'audience_brand_mentions_2th' => 'ブランド属性2位',
        'audience_brand_mentions_3rd' => 'ブランド属性3位',
        'audience_brand_mentions_4th' => 'ブランド属性4位',
        'audience_brand_mentions_5th' => 'ブランド属性5位',
        'aqs' => 'フォロワー実在率',
        'like_avg_30_post' => '直近30投稿の平均いいね数',
        'comment_avg_30_post' => '直近30投稿の平均コメント数',
        'like_rate_not_follower' => 'フォロワー外からのいいね',
        'active_rate' => 'いいねのアクティブ率',
        'email' => 'プロフィールに記載のコンタクト情報',
        'reel_like_rate' => '直近10投稿のリールのいいね数平均値',
        'reel_comment_rate' => '直近10投稿のリールのコメント平均',
        'reel_view_rate' => '直近10投稿のリールの再生数平均値',
        'reel_er_rate' => '直近10投稿のリールの平均エンゲージメント',
        //====================Youtube=================
        'status' => 'ステータス',
        'view_avg_30_post' => '直近30投稿の再生数平均値',
        'low_avg_30_post' => '直近30投稿の平均低評価数',
        'celebrity_ratio_among_registrants' => '登録者の中の有名人比率',
        'registrant_location_3rd' => '登録者の所在地３位',
        'registrant_location_largest_2nd' => '登録者の所在地２位',
        'registrants_1st' => '登録者の所在地１位',
        'female_45_64_registrants' => '登録者の45-64歳の女性の割合',
        'female_35_44_registrants' => '登録者の35-44歳の女性の割合',
        'female_25_34_registrants' => '登録者の25-34歳の女性の割合',
        'female_18_24_registrants' => '登録者の18-24歳の女性の割合',
        'female_13_17_registrants' => '登録者の13-17歳の女性の割合',
        'male_45_64_registrants' => '登録者の45-64歳の男性の割合',
        'male_35_44_registrants' => '登録者の35-44歳の男性の割合',
        'male_25_34_registrants' => '登録者の25-34歳の男性の割合',
        'male_18_24_registrants' => '登録者の18-24歳の男性の割合',
        'male_13_17_registrants' => '登録者の13-17歳の男性の割合',
        'female_registrants' => '登録者の女性割合',
        'male_registrants' => '登録者の男性割合',
        'number_registrants' => '登録者数',
        'url_youtube' => 'URL',
        'channel_url' => 'チャンネルURL',
        //=================tiktok====================
        'instagram_url' => 'インスタグラムURL',
        'celebrity_ratio_among_followers' => 'フォロワーの中の有名人比率',
        'follower_location_3rd' => 'フォロワーの所在地３位',
        'follower_location_2nd' => 'フォロワーの所在地２位',
        'follower_location_1st' => 'フォロワーの所在地１位',
    ],

    'kol_csv_file_name' => 'kol_export',

    'menu_admin' => [
        'user' => 'module.user',
        'role' => 'module.role',
        'genre' => 'module.genre',
        'plan' => 'module.plan'
    ],

    'menu_user' => [
        'kol' => 'module.kol',
        'insight-list' => 'module.insight-list',
        'campaign' => 'module.campaign',
        'setting' => 'module.setting'
    ],

    'kol_infos' => [
        [
            'basic' => [
                'username' => 'taylorswift',
                'title' => 'Taylor Swift',
                'avatar_url' => 'https://cdn.hypeauditor.com/img/instagram/user/11830955.jpg?w=320&till=1674097390&sign=137754e01b6fc9edb9e2d0f55f1429db',
            ],
            'metrics' => [
                'er' => '1.16',
                'subscribers_count' => '226769025'
            ],
        ],
        [
            'basic' => [
                'username' => 'vancityreynolds',
                'title' => 'Ryan Reynolds',
                'avatar_url' => 'https://cdn.hypeauditor.com/img/instagram/user/1942463581.jpg?w=320&till=1674098165&sign=08e3f95d387c94b52126b825223f87ac',
            ],
            'metrics' => [
                'er' => '1.18',
                'subscribers_count' => '45857334'
            ],
        ],
        [
            'basic' => [
                'username' => 'kevinhart4real',
                'title' => 'Kevin Hart',
                'avatar_url' => 'https://cdn.hypeauditor.com/img/instagram/user/6590609.jpg?w=320&till=1674098245&sign=428fb2be77bad0c8877398d37bad82f2',
            ],
            'metrics' => [
                'er' => '0.09',
                'subscribers_count' => '155039259'
            ],
        ],
        [
            'basic' => [
                'username' => 'supersaf',
                'title' => 'SuperSaf',
                'avatar_url' => 'https://cdn.hypeauditor.com/img/instagram/user/41428916.jpg?w=320&till=1674098340&sign=f440bcef026a9f129e335890f2377568',
            ],
            'metrics' => [
                'er' => '1.83',
                'subscribers_count' => '529231'
            ],
        ],
        [
            'basic' => [
                'username' => 'selenagomez',
                'title' => 'Selena Gomez',
                'avatar_url' => 'https://cdn.hypeauditor.com/img/instagram/user/460563723.jpg?w=320&till=1674098404&sign=6d026056d3295fff26a3ce2f51b6882a',
            ],
            'metrics' => [
                'er' => '0.7',
                'subscribers_count' => '351492414'
            ],
        ],
        [
            'basic' => [
                'username' => 'pepamack',
                'title' => 'Petra',
                'avatar_url' => 'https://cdn.hypeauditor.com/img/instagram/user/316719376.jpg?w=320&till=1674098485&sign=4e212d5d81a82b91a3236c928b0a6bd0',
            ],
            'metrics' => [
                'er' => '0.749461',
                'subscribers_count' => '1051585'
            ],
        ],
        [
            'basic' => [
                'username' => 'kendalljenner',
                'title' => 'Kendall',
                'avatar_url' => 'https://cdn.hypeauditor.com/img/instagram/user/6380930.jpg?w=320&till=1674098702&sign=9866747cb6e12bd123b2c35133f6b619',
            ],
            'metrics' => [
                'er' => '0.89',
                'subscribers_count' => '260554636'
            ],
        ],
        [
            'basic' => [
                'username' => 'fcbarcelona',
                'title' => 'FC Barcelona',
                'avatar_url' => 'https://cdn.hypeauditor.com/img/instagram/user/260375673.jpg?w=320&till=1674098749&sign=ef7d691b7d2d6d17045fa5cceb7fc471',
            ],
            'metrics' => [
                'er' => '0.34',
                'subscribers_count' => '112673770'
            ],
        ],
        [
            'basic' => [
                'username' => 'theshilpashetty',
                'title' => 'Shilpa Shetty Kundra',
                'avatar_url' => 'https://cdn.hypeauditor.com/img/instagram/user/1904097264.jpg?w=320&till=1674098825&sign=89b6ea598b251337fe1b310bb3cbd845',
            ],
            'metrics' => [
                'er' => '0.56',
                'subscribers_count' => '26807344'
            ],
        ],
        [
            'basic' => [
                'username' => 'tarynwilliams',
                'title' => 'Taryn Williams',
                'avatar_url' => 'https://cdn.hypeauditor.com/img/instagram/user/40507182.jpg?w=320&till=1674098881&sign=0fe2726db44d64e4248add6d6645e24a',
            ],
            'metrics' => [
                'er' => '0.83',
                'subscribers_count' => '22017'
            ],
        ],
        [
            'basic' => [
                'username' => 'kobebryant',
                'title' => 'Kobe Bryant',
                'avatar_url' => 'https://cdn.hypeauditor.com/img/instagram/user/351564405.jpg?w=320&till=1674100243&sign=cdbbac85a243afd7f765504d660fabae',
            ],
            'metrics' => [
                'er' => '7.31',
                'subscribers_count' => '21107168'
            ],
        ],
        [
            'basic' => [
                'username' => 'nathanwpyle',
                'title' => 'Nathan W Pyle',
                'avatar_url' => 'https://cdn.hypeauditor.com/img/instagram/user/213194044.jpg?w=320&till=1674100064&sign=b69916f1d77dded42cacf303d332bb0d',
            ],
            'metrics' => [
                'er' => '5.31',
                'subscribers_count' => '626007'
            ],
        ],
    ],

    'countries' => [
        'af' => 'Afghanistan',
        'ax' => 'Land Islands',
        'al' => 'Albania',
        'dz' => 'Algeria',
        'as' => 'American Samoa',
        'ad' => 'AndorrA',
        'ao' => 'Angola',
        'ai' => 'Anguilla',
        'aq' => 'Antarctica',
        'ag' => 'Antigua and Barbuda',
        'ar' => 'Argentina',
        'am' => 'Armenia',
        'aw' => 'Aruba',
        'au' => 'Australia',
        'at' => 'Austria',
        'az' => 'Azerbaijan',
        'bs' => 'Bahamas',
        'bh' => 'Bahrain',
        'bd' => 'Bangladesh',
        'bb' => 'Barbados',
        'by' => 'Belarus',
        'be' => 'Belgium',
        'bz' => 'Belize',
        'bj' => 'Benin',
        'bm' => 'Bermuda',
        'bt' => 'Bhutan',
        'bo' => 'Bolivia',
        'ba' => 'Bosnia and Herzegovina',
        'bw' => 'Botswana',
        'bv' => 'Bouvet Island',
        'br' => 'Brazil',
        'io' => 'British Indian Ocean Territory',
        'bn' => 'Brunei Darussalam',
        'bg' => 'Bulgaria',
        'bf' => 'Burkina Faso',
        'bi' => 'Burundi',
        'kh' => 'Cambodia',
        'cm' => 'Cameroon',
        'ca' => 'Canada',
        'cv' => 'Cape Verde',
        'ky' => 'Cayman Islands',
        'cf' => 'Central African Republic',
        'td' => 'Chad',
        'cl' => 'Chile',
        'cn' => 'China',
        'cx' => 'Christmas Island',
        'cc' => 'Cocos (Keeling) Islands',
        'co' => 'Colombia',
        'km' => 'Comoros',
        'cg' => 'Congo',
        'cd' => 'Congo, The Democratic Republic of the',
        'ck' => 'Cook Islands',
        'cr' => 'Costa Rica',
        'ci' => 'Cote D Ivoire',
        'hr' => 'Croatia',
        'cu' => 'Cuba',
        'cy' => 'Cyprus',
        'cz' => 'Czech Republic',
        'dk' => 'Denmark',
        'dj' => 'Djibouti',
        'dm' => 'Dominica',
        'do' => 'Dominican Republic',
        'ec' => 'Ecuador',
        'eg' => 'Egypt',
        'sv' => 'El Salvador',
        'gq' => 'Equatorial Guinea',
        'er' => 'Eritrea',
        'ee' => 'Estonia',
        'et' => 'Ethiopia',
        'fk' => 'Falkland Islands (Malvinas)',
        'fo' => 'Faroe Islands',
        'fj' => 'Fiji',
        'fi' => 'Finland',
        'fr' => 'France',
        'gf' => 'French Guiana',
        'pf' => 'French Polynesia',
        'tf' => 'French Southern Territories',
        'ga' => 'Gabon',
        'gm' => 'Gambia',
        'ge' => 'Georgia',
        'de' => 'Germany',
        'gh' => 'Ghana',
        'gi' => 'Gibraltar',
        'gr' => 'Greece',
        'gl' => 'Greenland',
        'gd' => 'Grenada',
        'gp' => 'Guadeloupe',
        'gu' => 'Guam',
        'gt' => 'Guatemala',
        'gg' => 'Guernsey',
        'gn' => 'Guinea',
        'gw' => 'Guinea-Bissau',
        'gy' => 'Guyana',
        'ht' => 'Haiti',
        'hm' => 'Heard Island and Mcdonald Islands',
        'va' => 'Holy See (Vatican City State)',
        'hn' => 'Honduras',
        'hk' => 'Hong Kong',
        'hu' => 'Hungary',
        'is' => 'Iceland',
        'in' => 'India',
        'id' => 'Indonesia',
        'ir' => 'Iran, Islamic Republic Of',
        'iq' => 'Iraq',
        'ie' => 'Ireland',
        'im' => 'Isle of Man',
        'il' => 'Israel',
        'it' => 'Italy',
        'jm' => 'Jamaica',
        'jp' => 'Japan',
        'je' => 'Jersey',
        'jo' => 'Jordan',
        'kz' => 'Kazakhstan',
        'ke' => 'Kenya',
        'ki' => 'Kiribati',
        'kp' => 'Korea',
        'kr' => 'Korea',
        'kw' => 'Kuwait',
        'kg' => 'Kyrgyzstan',
        'la' => 'Laos',
        'lv' => 'Latvia',
        'lb' => 'Lebanon',
        'ls' => 'Lesotho',
        'lr' => 'Liberia',
        'ly' => 'Libyan Arab Jamahiriya',
        'li' => 'Liechtenstein',
        'lt' => 'Lithuania',
        'lu' => 'Luxembourg',
        'mo' => 'Macao',
        'mk' => 'Macedonia, The Former Yugoslav Republic of',
        'mg' => 'Madagascar',
        'mw' => 'Malawi',
        'my' => 'Malaysia',
        'mv' => 'Maldives',
        'ml' => 'Mali',
        'mt' => 'Malta',
        'mh' => 'Marshall Islands',
        'mq' => 'Martinique',
        'mr' => 'Mauritania',
        'mu' => 'Mauritius',
        'yt' => 'Mayotte',
        'mx' => 'Mexico',
        'fm' => 'Micronesia, Federated States of',
        'md' => 'Moldova, Republic of',
        'mc' => 'Monaco',
        'mn' => 'Mongolia',
        'me' => 'Montenegro',
        'ms' => 'Montserrat',
        'ma' => 'Morocco',
        'mz' => 'Mozambique',
        'mm' => 'Myanmar',
        'na' => 'Namibia',
        'nr' => 'Nauru',
        'np' => 'Nepal',
        'nl' => 'Netherlands',
        'an' => 'Netherlands Antilles',
        'nc' => 'New Caledonia',
        'nz' => 'New Zealand',
        'ni' => 'Nicaragua',
        'ne' => 'Niger',
        'ng' => 'Nigeria',
        'nu' => 'Niue',
        'nf' => 'Norfolk Island',
        'mp' => 'Northern Mariana Islands',
        'no' => 'Norway',
        'om' => 'Oman',
        'pk' => 'Pakistan',
        'pw' => 'Palau',
        'ps' => 'Palestinian Territory, Occupied',
        'pa' => 'Panama',
        'pg' => 'Papua New Guinea',
        'py' => 'Paraguay',
        'pe' => 'Peru',
        'ph' => 'Philippines',
        'pn' => 'Pitcairn',
        'pl' => 'Poland',
        'pt' => 'Portugal',
        'pr' => 'Puerto Rico',
        'qa' => 'Qatar',
        're' => 'Reunion',
        'ro' => 'Romania',
        'ru' => 'Russian Federation',
        'rw' => 'RWANDA',
        'sh' => 'Saint Helena',
        'kn' => 'Saint Kitts and Nevis',
        'lc' => 'Saint Lucia',
        'pm' => 'Saint Pierre and Miquelon',
        'vc' => 'Saint Vincent and the Grenadines',
        'ws' => 'Samoa',
        'sm' => 'San Marino',
        'st' => 'Sao Tome and Principe',
        'sa' => 'Saudi Arabia',
        'sn' => 'Senegal',
        'rs' => 'Serbia',
        'sc' => 'Seychelles',
        'sl' => 'Sierra Leone',
        'sg' => 'Singapore',
        'sk' => 'Slovakia',
        'si' => 'Slovenia',
        'sb' => 'Solomon Islands',
        'so' => 'Somalia',
        'za' => 'South Africa',
        'gs' => 'South Georgia and the South Sandwich Islands',
        'es' => 'Spain',
        'lk' => 'Sri Lanka',
        'sd' => 'Sudan',
        'sr' => 'Suriname',
        'sj' => 'Svalbard and Jan Mayen',
        'sz' => 'Swaziland',
        'se' => 'Sweden',
        'ch' => 'Switzerland',
        'sy' => 'Syrian Arab Republic',
        'tw' => 'Taiwan, Province of China',
        'tj' => 'Tajikistan',
        'tz' => 'Tanzania, United Republic of',
        'th' => 'Thailand',
        'tl' => 'Timor-Leste',
        'tg' => 'Togo',
        'tk' => 'Tokelau',
        'to' => 'Tonga',
        'tt' => 'Trinidad and Tobago',
        'tn' => 'Tunisia',
        'tr' => 'Turkey',
        'tm' => 'Turkmenistan',
        'tc' => 'Turks and Caicos Islands',
        'tv' => 'Tuvalu',
        'ug' => 'Uganda',
        'ua' => 'Ukraine',
        'ae' => 'United Arab Emirates',
        'gb' => 'United Kingdom',
        'us' => 'United States',
        'um' => 'United States Minor Outlying Islands',
        'uy' => 'Uruguay',
        'uz' => 'Uzbekistan',
        'vu' => 'Vanuatu',
        've' => 'Venezuela',
        'vn' => 'Viet Nam',
        'vg' => 'Virgin Islands, British',
        'vi' => 'Virgin Islands, U.S.',
        'wf' => 'Wallis and Futuna',
        'eh' => 'Western Sahara',
        'ye' => 'Yemen',
        'zm' => 'Zambia',
        'zw' => 'Zimbabwe',
    ],

    'instagram_url' => 'https://www.instagram.com/',
    'youtube_url' => 'https://www.youtube.com/channel/',
    'tiktok_url' => 'https://www.tiktok.com/@',
    'kol_infos_tiktok' => [
      [
        'basic' => [
          'id'=> '6557821753438371845',
          'username'=> 'littlebig',
          'title'=> 'littlebig',
          'avatar_url'=> 'https://cdn.hypeauditor.com/img/tiktok/user/6557821753438371845.jpg?w=150&till=1670050800&sign=7d4da05e2c860e1f20ad227d0c50dc8e',
          'description'=> 'Russian punk-rave band LITTLE BIG'
        ],
        'metrics' => [
          'er' => '1.16',
          'subscribers_count' => '226769025'
        ],
      ]
    ],
    'campaign_social_type' => [
        'instagram' => 1,
        'youtube' => 2,
        'tiktok' => 3,
    ],
    'ages_mapping_tiktok' => '45-64',
    'ages_group_merge_tiktok' => ['45-54', '55-64'],
    'ages_group_tiktok' => [
        '13-17' => [
            'male' => 0,
            'female' => 0,
        ],
        '18-24' => [
            'male' => 0,
            'female' => 0,
        ],
        '25-34' => [
            'male' => 0,
            'female' => 0,
        ],
        '35-44' => [
            'male' => 0,
            'female' => 0,
        ],
        '45-64' => [
            'male' => 0,
            'female' => 0,
        ],
    ],
    'admin_password' => '12345678',
    'user_role_type' => [
      'admin' => 1,
      'user' => 2,
    ],

    'Kol_status' => [
        0 => '社内確認中',
        1 => '交渉中',
        2 => 'NG',
        3 => '中止',
        4 => '商品発送済み',
        5 => '手書き待ち',
        6 => '本投稿待ち',
        7 => 'インサイト待ち',
        8 => '完了',
    ]
];
